### ISSUE TITLE
substring not found

### ISSUE THREAD

**Issue by massicotjgab** [massicotjgab/Markedown_to_HTML_converter#1]
When i test with my test document, I have this issue 

Traceback (most recent call last):
  File "md_html_conv.py", line 82, in <module>
    em_func(new_line)  # important text function
  File "md_html_conv.py", line 38, in em_func
    index_star = reading.index("*")
ValueError: substring not found

I don't understand where is th issue

**Comment by padmano** [comment]
Have submitted #2 #3 PRs for the same. Good project.

**Comment by massicotjgab** [comment]
Thank you for your help!
I will Test that later and come back to confirm the good fonctionning!

**Comment by padmano** [comment]
Probably you should close this issue.

**Comment by massicotjgab** [comment]
I close it. I'll try it later and confirm the functionning later.
